//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejemplo03
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EjemploMVCEntities : DbContext
    {
        public EjemploMVCEntities()
            : base("name=EjemploMVCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Proveedor> Proveedor { get; set; }
    
        public virtual ObjectResult<usp_listaDatos_Result> usp_listaDatos_metodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listaDatos_Result>("usp_listaDatos_metodo");
        }
    }
}
